# agents/writer_agent.py

from langchain_groq import ChatGroq
from state.research_state import ResearchState
import os
from dotenv import load_dotenv

load_dotenv()

llm = ChatGroq(
    api_key=os.getenv("GROQ_API_KEY"),
    model_name="llama-3.3-70b-versatile",
    max_retries=3,
)

def writer_agent(state: ResearchState) -> ResearchState:
    """
    Reads:  topic, analysis, critic_feedback, confidence_scores
    Writes: final_report, current_step
    """
    topic = state["topic"]
    analysis = state["analysis"]
    critic_feedback = state["critic_feedback"]
    confidence = state["confidence_scores"].get("score", 70)

    prompt = f"""You are a professional report writer.

Topic: {topic}

Research Analysis:
{analysis}

Quality Review Notes:
{critic_feedback}

Write a professional research report with these exact sections:

# {topic} — Research Report

## Executive Summary
[3-4 sentences capturing the most important findings]

## Key Findings
[5 numbered findings, each with supporting evidence]

## Analysis
[Detailed examination of patterns, causes, implications]

## Challenges & Opportunities
[Balanced view of problems and possibilities]

## Conclusion
[Forward-looking summary with actionable insights]

## Sources
[List all URLs from the research]

---
Report Confidence Score: {confidence}/100
Note: This report was generated by AI agents. Claims are 
cross-referenced against search results but independent 
verification is recommended for critical decisions."""

    response = llm.invoke(prompt)

    return {
        **state,
        "final_report": response.content,
        "current_step": "report_complete"
    }